version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 20
  target-branch: develop
- package-ecosystem: npm
  directory: "/webapp/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 20
  target-branch: develop
