# See https://www.gitpod.io/docs/introduction/languages/java

image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build cache
    init: |
      rm -f /workspace/.r

      # Frontend cache
      pushd webapp
      npm ci
      popd

      # Fix API server address for Gitpod VSCode Web
      echo "REACT_APP_API_URL=$(gp url 8080)" > webapp/.env.local

      # Backend cache
      ./gradlew server-app:unpack

      touch /workspace/.r
    openMode: tab-before
  
  - name: Backend
    command: |
      until test -e /workspace/.r; do sleep 1; done
      ./gradlew server-app:bootRun --args='--spring.profiles.active=dev'
    openMode: split-left
  - name: Frontend
    command: until test -e /workspace/.r; do sleep 1; done && cd webapp && npm run start
    openMode: split-right

vscode:
  extensions:
    - vscjava.vscode-java-pack
