# See https://www.gitpod.io/docs/introduction/languages/java

image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build cache
    openMode: tab-before
    init: |
      (
        # Frontend cache
        rm -f /workspace/.f
        pushd webapp
        npm ci
        popd
        touch /workspace/.f
      ) &

      # Backend cache
      rm -f /workspace/.b
      ./gradlew server-app:unpack
      touch /workspace/.b

  
  - name: Backend
    openMode: split-left
    command: |
      until test -e /workspace/.b; do sleep 1; done
      ./gradlew server-app:bootRun --args='--spring.profiles.active=dev'

  - name: Frontend
    openMode: split-right
    command: |
      # Fix API server address for Gitpod VSCode Web
      echo "REACT_APP_API_URL=$(gp url 8080)" > webapp/.env.local

      # Schedule auto-refresh for the webapp preview window after backend is fully up,
      # as the webapp will probably have an error on the first render.
      (gp ports await 8080 && gp preview "$(gp url 3000)") &

      until test -e /workspace/.f; do sleep 1; done
      cd webapp && BROWSER='' npm run start

ports:
  - name: Backend
    port: 8080
    visibility: public
    onOpen: ignore
  
  - name: Frontend
    port: 3000
    visibility: public
    onOpen: open-preview

  - port: 15000-50000
    onOpen: ignore
    description: Misc.

vscode:
  extensions:
    - vscjava.vscode-java-pack
