spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/schema.xml
  jpa:
    show-sql: true
logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
tolgee:
  sentry:
    enabled: false
  authentication:
    enabled: true
    #   jwt-secret-file: /<user home>/.tolgee/jwt.secret
    jwt-secret: ldkajsldkjsaldkasjldk ajldkj aslkajsldas dsalk jdslk djaslkdj salkd jalskd jalsk
    jwt-expiration: 604800000
    #    native-enabled: true
    registrations-allowed: true
    initial-username: "admin"
    initial-password: "admin"
    needs-email-verification: true
  #    github:
  #      client-id: <client id obtained from github>
  #      client-secret: <client secret obtained from github>
  #      authorization-url: "https://github.com/login/oauth/access_token"
  #      user-url: "https://api.github.com/user"
  #    ldap: ##experimental feature
  #      base-dn:
  #      enabled:
  #      port:
  #      principal-password:
  #      security-principal:
  #      urls:
  #      user-dn-pattern:
  smtp:
    from: Tolgee <no-reply@tolgee.io>
    host: email-smtp.eu-central-1.amazonaws.com
    username: AKIA2LJQBN6TVTOOEAH2
    password: BDxUBkKRWXrAMSolpTgeu/JECiSz2IOk1myuNar67CBG
    auth: true
    port: 465
    ssl-enabled: true
server:
  compression:
    enabled: true
    mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json"
    min-response-size: 1024
sentry:
  dsn: ${tolgee.sentry.server-dsn:}
