version: '3'
services:
  app:
    container_name: tolgee_e2e
    image: tolgee/tolgee:local
    ports:
      - 8201:8201
      - 8091:8091
    environment:
      - spring.profiles.active=e2e
      - spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
      - tolgee.smtp.host=fakesmtp
      - tolgee.smtp.port=1025
  postgres:
    image: postgres:13
    volumes:
      - e2e-db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "25432:5432"
  fakesmtp:
    image: reachfive/fake-smtp-server:0.8.1
    ports:
      - "21025:1025"
      - "21080:1080"
volumes:
  e2e-db-data:
